In [1]:
# Dependencies
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import session
from sqlalchemy import inspect
from sqlalchemy import create_engine, func
from getpass import getpass

In [2]:
pip install psycopg2

Note: you may need to restart the kernel to use updated packages.


In [3]:
import psycopg2

In [8]:
### Connect to database
# Store password
from getpass import getpass
password = getpass("enter database password")

enter database password········


In [9]:
# connect to database
engine = create_engine(f"postgresql://postgres:{password}@localhost:5432/COVID-project")

In [10]:
# Get the names of the tables 
inspector = inspect(engine)
inspector.get_table_names()

['lat_long',
 'latest_vax',
 'latest_deaths',
 'econ',
 'lat_long_econ',
 'lat_long_econ_deaths',
 'all_tables_merged']

In [11]:
# Get data from database and convert to dataframe
df = pd.read_sql_table('all_tables_merged', engine)
df

fips  st      lat       lng  population  unemployment_rate_2021  \
0     36005  NY  40.8500  -73.8661     1427056                    13.6   
1      1001  AL  32.5349  -86.6427       55639                     2.8   
2      1003  AL  30.7276  -87.7226      218289                     3.0   
3      1005  AL  31.8696  -85.3932       25026                     5.7   
4      1007  AL  32.9986  -87.1265       22374                     3.5   
...     ...  ..      ...       ...         ...                     ...   
3138  56039  WY  43.9347 -110.5900       23356                     3.2   
3139  56041  WY  41.2876 -110.5480       20374                     5.0   
3140  56043  WY  43.9050 -107.6830        7933                     4.0   
3141  56045  WY  43.8405 -104.5680        6942                     3.2   
3142  15005  HI  21.1709 -156.9470         436                     NaN   

      median_household_income_2020    county    cases  deaths  vax_pct  \
0                          44906.0      None      NaN     NaN     76.6   
1                          67565.0   Autauga  18233.0   226.0     45.1   
2                          71135.0   Baldwin  65088.0   702.0     52.2   
3                          38866.0   Barbour   6826.0   101.0     46.7   
4                          50907.0      Bibb   7450.0   107.0     35.8   
...                            ...       ...      ...     ...      ...   
3138                       92488.0     Teton  11583.0    16.0     94.2   
3139                       71246.0     Uinta   6102.0    41.0     52.7   
3140                       58532.0  Washakie   2642.0    47.0     44.8   
3141                       58901.0    Weston   1812.0    21.0     38.6   
3142                           NaN   Kalawao      1.0     0.0      NaN   

      cases_100000  deaths_100000  
0              NaN            NaN  
1        32770.200       406.1900  
2        29817.400       321.5920  
3        27275.600       403.5800  
4        33297.600       478.2340  
...            ...            ...  
3138     49593.300        68.5049  
3139     29949.900       201.2370  
3140     33303.900       592.4620  
3141     26102.000       302.5060  
3142       229.358         0.0000  

[3143 rows x 13 columns]

In [12]:
# Drop rows with null values
df = df.dropna(subset=['vax_pct'])
df = df.dropna(subset=['cases'])
df

fips  st      lat       lng  population  unemployment_rate_2021  \
1      1001  AL  32.5349  -86.6427       55639                     2.8   
2      1003  AL  30.7276  -87.7226      218289                     3.0   
3      1005  AL  31.8696  -85.3932       25026                     5.7   
4      1007  AL  32.9986  -87.1265       22374                     3.5   
5      1009  AL  33.9809  -86.5674       57755                     2.4   
...     ...  ..      ...       ...         ...                     ...   
3137  56037  WY  41.6595 -108.8800       43352                     5.6   
3138  56039  WY  43.9347 -110.5900       23356                     3.2   
3139  56041  WY  41.2876 -110.5480       20374                     5.0   
3140  56043  WY  43.9050 -107.6830        7933                     4.0   
3141  56045  WY  43.8405 -104.5680        6942                     3.2   

      median_household_income_2020      county    cases  deaths  vax_pct  \
1                          67565.0     Autauga  18233.0   226.0     45.1   
2                          71135.0     Baldwin  65088.0   702.0     52.2   
3                          38866.0     Barbour   6826.0   101.0     46.7   
4                          50907.0        Bibb   7450.0   107.0     35.8   
5                          55203.0      Blount  16673.0   254.0     32.4   
...                            ...         ...      ...     ...      ...   
3137                       70583.0  Sweetwater  12117.0   130.0     51.4   
3138                       92488.0       Teton  11583.0    16.0     94.2   
3139                       71246.0       Uinta   6102.0    41.0     52.7   
3140                       58532.0    Washakie   2642.0    47.0     44.8   
3141                       58901.0      Weston   1812.0    21.0     38.6   

      cases_100000  deaths_100000  
1          32770.2       406.1900  
2          29817.4       321.5920  
3          27275.6       403.5800  
4          33297.6       478.2340  
5          28868.5       439.7890  
...            ...            ...  
3137       27950.3       299.8710  
3138       49593.3        68.5049  
3139       29949.9       201.2370  
3140       33303.9       592.4620  
3141       26102.0       302.5060  

[3116 rows x 13 columns]

In [13]:
# Creating median split codes for cases, deaths, vax https://www.appsloveworld.com/pandas/100/383/performing-a-median-split-on-a-pandas-dataframe
df["median_split_cases"] = (df.cases_100000<df.cases_100000.quantile()).replace({True:0, False:1})
df["median_split_deaths"] = (df.deaths_100000<df.deaths_100000.quantile()).replace({True:0, False:1})
df["median_split_vax_pct"] = (df.vax_pct<df.vax_pct.quantile()).replace({True:0, False:1})
df

fips  st      lat       lng  population  unemployment_rate_2021  \
1      1001  AL  32.5349  -86.6427       55639                     2.8   
2      1003  AL  30.7276  -87.7226      218289                     3.0   
3      1005  AL  31.8696  -85.3932       25026                     5.7   
4      1007  AL  32.9986  -87.1265       22374                     3.5   
5      1009  AL  33.9809  -86.5674       57755                     2.4   
...     ...  ..      ...       ...         ...                     ...   
3137  56037  WY  41.6595 -108.8800       43352                     5.6   
3138  56039  WY  43.9347 -110.5900       23356                     3.2   
3139  56041  WY  41.2876 -110.5480       20374                     5.0   
3140  56043  WY  43.9050 -107.6830        7933                     4.0   
3141  56045  WY  43.8405 -104.5680        6942                     3.2   

      median_household_income_2020      county    cases  deaths  vax_pct  \
1                          67565.0     Autauga  18233.0   226.0     45.1   
2                          71135.0     Baldwin  65088.0   702.0     52.2   
3                          38866.0     Barbour   6826.0   101.0     46.7   
4                          50907.0        Bibb   7450.0   107.0     35.8   
5                          55203.0      Blount  16673.0   254.0     32.4   
...                            ...         ...      ...     ...      ...   
3137                       70583.0  Sweetwater  12117.0   130.0     51.4   
3138                       92488.0       Teton  11583.0    16.0     94.2   
3139                       71246.0       Uinta   6102.0    41.0     52.7   
3140                       58532.0    Washakie   2642.0    47.0     44.8   
3141                       58901.0      Weston   1812.0    21.0     38.6   

      cases_100000  deaths_100000  median_split_cases  median_split_deaths  \
1          32770.2       406.1900                   1                    1   
2          29817.4       321.5920                   1                    0   
3          27275.6       403.5800                   0                    1   
4          33297.6       478.2340                   1                    1   
5          28868.5       439.7890                   1                    1   
...            ...            ...                 ...                  ...   
3137       27950.3       299.8710                   0                    0   
3138       49593.3        68.5049                   1                    0   
3139       29949.9       201.2370                   1                    0   
3140       33303.9       592.4620                   1                    1   
3141       26102.0       302.5060                   0                    0   

      median_split_vax_pct  
1                        0  
2                        1  
3                        0  
4                        0  
5                        0  
...                    ...  
3137                     1  
3138                     1  
3139                     1  
3140                     0  
3141                     0  

[3116 rows x 16 columns]

In [14]:
### Logistic regression to predict case rate
# Seaparate features from the target

y_cases = df["median_split_cases"]
X_econ = df[["unemployment_rate_2021", "median_household_income_2020"]]

In [15]:
X_econ_train, X_econ_test, y_cases_train, y_cases_test = train_test_split(X_econ, y_cases, random_state=42)
X_econ_train.shape

(2337, 2)

In [16]:
import sklearn as skl
# Create scaler instance
X_econ_scaler = skl.preprocessing.StandardScaler()

# Fit the scaler
X_econ_scaler.fit(X_econ_train)

# Scale the data
X_econ_train_scaled = X_econ_scaler.transform(X_econ_train)
X_econ_test_scaled = X_econ_scaler.transform(X_econ_test)

C:\Users\josep\anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.
  FutureWarning,
C:\Users\josep\anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.
  FutureWarning,
C:\Users\josep\anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.
  FutureWarning,


In [17]:
# Create logistic regression model

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=200)        

In [18]:
# Fit model with training data
classifier.fit(X_econ_train_scaled, y_cases_train)

LogisticRegression(max_iter=200)

In [19]:
# Create predicitions with test set
y_cases_pred = classifier.predict(X_econ_test_scaled)

# View as dataframe
cases_results = pd.DataFrame({"Y_Cases_Prediction": y_cases_pred, "Actual (y-test)": y_cases_test}).reset_index(drop=True)
cases_results.head(5)

Y_Cases_Prediction  Actual (y-test)
0                   1                1
1                   0                1
2                   0                0
3                   0                1
4                   1                1

In [20]:
# Get accuracy score

from sklearn.metrics import accuracy_score
print("Accuracy score predicting case rate")
print(accuracy_score(y_cases_test, y_cases_pred))

Accuracy score predicting case rate
0.5558408215661104


In [21]:
# Get confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
cases_matrix = confusion_matrix(y_cases_test, y_cases_pred)

# Create a DataFrame from the confusion matrix.
matrix_cases_df = pd.DataFrame(cases_matrix, 
                         index=["Actual 0-low_cases", "Actual 1-high_cases"], 
                         columns=["Predicted 0-low_cases", "Predicted 1-high_cases"])

matrix_cases_df

Predicted 0-low_cases  Predicted 1-high_cases
Actual 0-low_cases                     211                     172
Actual 1-high_cases                    174                     222

In [22]:
# Classification report 
cases_report = classification_report(y_cases_test, y_cases_pred)
print(cases_report)

              precision    recall  f1-score   support

           0       0.55      0.55      0.55       383
           1       0.56      0.56      0.56       396

    accuracy                           0.56       779
   macro avg       0.56      0.56      0.56       779
weighted avg       0.56      0.56      0.56       779



In [23]:
## Creating 3d scatterplot of predictions
X_econ_test_scaled

array([[ 2.25012101, -0.16172054],
       [-1.02162759,  3.12298936],
       [-0.78368223,  0.04114238],
       ...,
       [-0.24830519, -0.72206921],
       [-1.14060026, -0.49826926],
       [ 1.35782594,  2.5292546 ]])

In [24]:
X_cases = X_econ_test_scaled[:, 0]
X_cases

array([ 2.25012101, -1.02162759, -0.78368223, -0.7241959 , -1.02162759,
        0.58450354, -1.25957294,  0.76296256, -0.90265491, -1.61649097,
       -0.36727787,  2.78549806,  0.0491265 ,  0.10861284,  0.10861284,
       -0.12933251,  0.70347622,  0.28707185,  0.22758552, -1.43803195,
       -0.48625054, -1.25957294, -0.78368223,  0.8224489 , -0.06984618,
        2.19063468,  0.58450354,  0.28707185, -0.84316857, -0.12933251,
       -1.73546364, -0.60522322, -1.61649097, -0.12933251, -1.37854562,
        0.22758552,  1.00090791,  0.0491265 , -0.96214125,  0.22758552,
       -1.43803195,  0.40604453,  0.0491265 ,  0.52501721,  1.06039425,
       -0.18881885, -1.49751829, -0.96214125, -1.67597731, -0.7241959 ,
        1.00090791, -0.12933251,  0.46553087, -1.31905928, -1.2000866 ,
        0.16809918,  1.35782594, -1.37854562, -1.08111392,  0.16809918,
       -0.36727787, -1.14060026, -0.78368223,  0.28707185,  0.0491265 ,
       -1.08111392,  0.22758552,  0.16809918, -0.7241959 ,  0.16

In [25]:
Y_cases = X_econ_test_scaled[:, 1]
Y_cases

array([-1.61720536e-01,  3.12298936e+00,  4.11423772e-02,  2.90194092e-01,
       -6.31035540e-01, -8.62333213e-01,  3.54773534e-01,  1.17740104e+00,
       -8.73799079e-02, -4.91266671e-01, -1.50013478e+00, -1.02933438e+00,
        8.29959396e-01, -1.59810031e+00, -6.57065370e-01,  9.45820432e-01,
       -1.28128615e+00, -1.12786577e+00,  1.65067002e-01,  9.51118342e-02,
        1.43493366e-01, -3.52275867e-01, -6.64428708e-02,  6.69890089e-01,
        2.46460442e+00,  2.31535730e+00, -6.33157537e-01, -1.00819222e-01,
        1.45460458e+00, -1.44326526e+00,  3.84835158e-01, -3.12665256e-01,
        7.90914651e-01, -2.46741883e-01,  4.52526863e-01,  2.21151374e-02,
       -1.33992400e+00, -1.31318684e+00,  3.65029853e-01, -2.74893710e-01,
       -2.69800917e-01,  2.49077572e+00,  1.60569077e+00, -8.46630435e-01,
       -1.29338154e+00, -7.00566308e-01,  2.47882180e+00, -6.61309364e-01,
       -3.83822889e-01,  1.33244829e+00, -4.64812441e-01, -8.40052245e-01,
       -5.18640432e-01,  

In [26]:
Z = y_cases_test.values.reshape(-1,1)
Z

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
    

In [27]:
df_x_cases = pd.DataFrame(X_cases)
df_y_cases = pd.DataFrame(Y_cases)
df_z_cases = pd.DataFrame(Z)

In [29]:
df_x_cases.rename(columns = {0:'X_cases'}, inplace = True)
df_x_cases

X_cases
0    2.250121
1   -1.021628
2   -0.783682
3   -0.724196
4   -1.021628
..        ...
774 -0.486251
775 -1.200087
776 -0.248305
777 -1.140600
778  1.357826

[779 rows x 1 columns]

In [30]:
df_y_cases.rename(columns = {0:'y_cases'}, inplace = True)
df_y_cases

y_cases
0   -0.161721
1    3.122989
2    0.041142
3    0.290194
4   -0.631036
..        ...
774 -0.676163
775  0.816874
776 -0.722069
777 -0.498269
778  2.529255

[779 rows x 1 columns]

In [31]:
df_z_cases.rename(columns = {0:'z_cases'}, inplace = True)
df_z_cases

z_cases
0          1
1          1
2          0
3          1
4          1
..       ...
774        0
775        0
776        1
777        0
778        0

[779 rows x 1 columns]

In [34]:
df_xy_cases = pd.concat([df_x_cases, df_y_cases], axis=1,
)
df_xy_cases

X_cases   y_cases
0    2.250121 -0.161721
1   -1.021628  3.122989
2   -0.783682  0.041142
3   -0.724196  0.290194
4   -1.021628 -0.631036
..        ...       ...
774 -0.486251 -0.676163
775 -1.200087  0.816874
776 -0.248305 -0.722069
777 -1.140600 -0.498269
778  1.357826  2.529255

[779 rows x 2 columns]

In [35]:
df_xyz_cases = pd.concat([df_xy_cases, df_z_cases], axis=1
)
df_xyz_cases

X_cases   y_cases  z_cases
0    2.250121 -0.161721        1
1   -1.021628  3.122989        1
2   -0.783682  0.041142        0
3   -0.724196  0.290194        1
4   -1.021628 -0.631036        1
..        ...       ...      ...
774 -0.486251 -0.676163        0
775 -1.200087  0.816874        0
776 -0.248305 -0.722069        1
777 -1.140600 -0.498269        0
778  1.357826  2.529255        0

[779 rows x 3 columns]

In [36]:
import plotly.express as px  # for data visualization
import plotly.graph_objects as go # for data visualization

In [48]:
# Creating 3D scatterplot of predicting case rate
# Create a 3D scatter plot with predictions


fig_cases = px.scatter_3d(df_xyz_cases, x="X_cases", y="y_cases", z="z_cases", 
                 opacity=0.8,
                 labels=dict(X_cases="Unemployment Rate", 
                             y_cases="Median Income",
                             z_cases="Median Split for Case Rate",))
fig_cases.show()


In [50]:
### Logistic regression to predict death rate
# Seaparate features from the target

y_deaths = df["median_split_deaths"]
X_econ = df[["unemployment_rate_2021", "median_household_income_2020"]]

In [51]:
X_econ_train, X_econ_test, y_deaths_train, y_deaths_test = train_test_split(X_econ, y_deaths, random_state=42)
X_econ_train.shape

(2337, 2)

In [52]:
# Create scaler instance
X_econ_scaler = skl.preprocessing.StandardScaler()

# Fit the scaler
X_econ_scaler.fit(X_econ_train)

# Scale the data
X_econ_train_scaled = X_econ_scaler.transform(X_econ_train)
X_econ_test_scaled = X_econ_scaler.transform(X_econ_test)

C:\Users\josep\anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning:

Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.

C:\Users\josep\anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning:

Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.

C:\Users\josep\anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning:

Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.



In [53]:
# Fit model with training data
classifier.fit(X_econ_train_scaled, y_deaths_train)

LogisticRegression(max_iter=200)

In [54]:
# Create predicitions with test set
y_deaths_pred = classifier.predict(X_econ_test_scaled)

# View as dataframe
cases_results = pd.DataFrame({"Y_Deaths_Prediction": y_deaths_pred, "Actual (y-test)": y_deaths_test}).reset_index(drop=True)
cases_results.head(5)

Y_Deaths_Prediction  Actual (y-test)
0                    0                0
1                    0                0
2                    0                0
3                    0                1
4                    1                1

In [55]:
# Get accuracy score

print("Accuracy score predicting death rate")
print(accuracy_score(y_deaths_test, y_deaths_pred))

Accuracy score predicting death rate
0.7329910141206675


In [56]:
# Get confusion matrix

deaths_matrix = confusion_matrix(y_deaths_test, y_deaths_pred)

# Create a DataFrame from the confusion matrix.
matrix_deaths_df = pd.DataFrame(deaths_matrix, 
                         index=["Actual 0-low_deaths", "Actual 1-high_deaths"], 
                         columns=["Predicted 0-low_deaths", "Predicted 1-high_deaths"])

matrix_deaths_df


Predicted 0-low_deaths  Predicted 1-high_deaths
Actual 0-low_deaths                      270                      105
Actual 1-high_deaths                     103                      301

In [57]:
# Classification report 
deaths_report = classification_report(y_deaths_test, y_deaths_pred)
print(deaths_report)

              precision    recall  f1-score   support

           0       0.72      0.72      0.72       375
           1       0.74      0.75      0.74       404

    accuracy                           0.73       779
   macro avg       0.73      0.73      0.73       779
weighted avg       0.73      0.73      0.73       779



In [60]:
X_deaths = X_econ_test_scaled[:, 0]
X_deaths

array([ 2.25012101, -1.02162759, -0.78368223, -0.7241959 , -1.02162759,
        0.58450354, -1.25957294,  0.76296256, -0.90265491, -1.61649097,
       -0.36727787,  2.78549806,  0.0491265 ,  0.10861284,  0.10861284,
       -0.12933251,  0.70347622,  0.28707185,  0.22758552, -1.43803195,
       -0.48625054, -1.25957294, -0.78368223,  0.8224489 , -0.06984618,
        2.19063468,  0.58450354,  0.28707185, -0.84316857, -0.12933251,
       -1.73546364, -0.60522322, -1.61649097, -0.12933251, -1.37854562,
        0.22758552,  1.00090791,  0.0491265 , -0.96214125,  0.22758552,
       -1.43803195,  0.40604453,  0.0491265 ,  0.52501721,  1.06039425,
       -0.18881885, -1.49751829, -0.96214125, -1.67597731, -0.7241959 ,
        1.00090791, -0.12933251,  0.46553087, -1.31905928, -1.2000866 ,
        0.16809918,  1.35782594, -1.37854562, -1.08111392,  0.16809918,
       -0.36727787, -1.14060026, -0.78368223,  0.28707185,  0.0491265 ,
       -1.08111392,  0.22758552,  0.16809918, -0.7241959 ,  0.16

In [61]:
y_deaths = X_econ_test_scaled[:, 1]
y_deaths

array([-1.61720536e-01,  3.12298936e+00,  4.11423772e-02,  2.90194092e-01,
       -6.31035540e-01, -8.62333213e-01,  3.54773534e-01,  1.17740104e+00,
       -8.73799079e-02, -4.91266671e-01, -1.50013478e+00, -1.02933438e+00,
        8.29959396e-01, -1.59810031e+00, -6.57065370e-01,  9.45820432e-01,
       -1.28128615e+00, -1.12786577e+00,  1.65067002e-01,  9.51118342e-02,
        1.43493366e-01, -3.52275867e-01, -6.64428708e-02,  6.69890089e-01,
        2.46460442e+00,  2.31535730e+00, -6.33157537e-01, -1.00819222e-01,
        1.45460458e+00, -1.44326526e+00,  3.84835158e-01, -3.12665256e-01,
        7.90914651e-01, -2.46741883e-01,  4.52526863e-01,  2.21151374e-02,
       -1.33992400e+00, -1.31318684e+00,  3.65029853e-01, -2.74893710e-01,
       -2.69800917e-01,  2.49077572e+00,  1.60569077e+00, -8.46630435e-01,
       -1.29338154e+00, -7.00566308e-01,  2.47882180e+00, -6.61309364e-01,
       -3.83822889e-01,  1.33244829e+00, -4.64812441e-01, -8.40052245e-01,
       -5.18640432e-01,  

In [62]:
Z = y_deaths_test.values.reshape(-1,1)
Z

array([[0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
    

In [64]:
df_x_deaths = pd.DataFrame(X_deaths)
df_y_deaths = pd.DataFrame(y_deaths)
df_z_deaths = pd.DataFrame(Z)

In [65]:
df_x_deaths.rename(columns = {0:'X_deaths'}, inplace = True)
df_x_deaths

X_deaths
0    2.250121
1   -1.021628
2   -0.783682
3   -0.724196
4   -1.021628
..        ...
774 -0.486251
775 -1.200087
776 -0.248305
777 -1.140600
778  1.357826

[779 rows x 1 columns]

In [66]:
df_y_deaths.rename(columns = {0:'y_deaths'}, inplace = True)
df_y_deaths

y_deaths
0   -0.161721
1    3.122989
2    0.041142
3    0.290194
4   -0.631036
..        ...
774 -0.676163
775  0.816874
776 -0.722069
777 -0.498269
778  2.529255

[779 rows x 1 columns]

In [67]:
df_z_deaths.rename(columns = {0:'z_deaths'}, inplace = True)
df_z_deaths

z_deaths
0           0
1           0
2           0
3           1
4           1
..        ...
774         1
775         0
776         0
777         1
778         0

[779 rows x 1 columns]

In [68]:
df_xy_deaths = pd.concat([df_x_deaths, df_y_deaths], axis=1,
)
df_xy_deaths

X_deaths  y_deaths
0    2.250121 -0.161721
1   -1.021628  3.122989
2   -0.783682  0.041142
3   -0.724196  0.290194
4   -1.021628 -0.631036
..        ...       ...
774 -0.486251 -0.676163
775 -1.200087  0.816874
776 -0.248305 -0.722069
777 -1.140600 -0.498269
778  1.357826  2.529255

[779 rows x 2 columns]

In [69]:
df_xyz_deaths = pd.concat([df_xy_deaths, df_z_deaths], axis=1
)
df_xyz_deaths

X_deaths  y_deaths  z_deaths
0    2.250121 -0.161721         0
1   -1.021628  3.122989         0
2   -0.783682  0.041142         0
3   -0.724196  0.290194         1
4   -1.021628 -0.631036         1
..        ...       ...       ...
774 -0.486251 -0.676163         1
775 -1.200087  0.816874         0
776 -0.248305 -0.722069         0
777 -1.140600 -0.498269         1
778  1.357826  2.529255         0

[779 rows x 3 columns]

In [72]:
# Creating 3D scatterplot of predicting case rate
# Create a 3D scatter plot with predictions


fig_deaths = px.scatter_3d(df_xyz_deaths, x="X_deaths", y="y_deaths", z="z_deaths", 
                 opacity=0.8,
                 labels=dict(X_deaths="Unemployment Rate", 
                             y_deaths="Median Income",
                             z_deaths="Median Split for Death Rate",))
fig_deaths.show()

In [77]:
### Logistic regression to predict vax pct
# Seaparate features from the target

y_vax = df["median_split_vax_pct"]
X_econ = df[["unemployment_rate_2021", "median_household_income_2020"]]

In [78]:
X_econ_train, X_econ_test, y_vax_train, y_vax_test = train_test_split(X_econ, y_vax, random_state=42)
X_econ_train.shape

(2337, 2)

In [79]:
# Create scaler instance
X_econ_scaler = skl.preprocessing.StandardScaler()

# Fit the scaler
X_econ_scaler.fit(X_econ_train)

# Scale the data
X_econ_train_scaled = X_econ_scaler.transform(X_econ_train)
X_econ_test_scaled = X_econ_scaler.transform(X_econ_test)

C:\Users\josep\anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning:

Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.

C:\Users\josep\anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning:

Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.

C:\Users\josep\anaconda3\envs\PythonData\lib\site-packages\sklearn\utils\validation.py:1692: FutureWarning:

Feature names only support names that are all strings. Got feature names with dtypes: ['quoted_name']. An error will be raised in 1.2.



In [80]:
# Fit model with training data
classifier.fit(X_econ_train_scaled, y_vax_train)

LogisticRegression(max_iter=200)

In [81]:
# Create predicitions with test set
y_vax_pred = classifier.predict(X_econ_test_scaled)

# View as dataframe
vax_results = pd.DataFrame({"Y_Vax_Prediction": y_vax_pred, "Actual (y-test)": y_vax_test}).reset_index(drop=True)
vax_results.head(5)

Y_Vax_Prediction  Actual (y-test)
0                 1                1
1                 1                1
2                 0                1
3                 0                1
4                 0                0

In [82]:
# Get accuracy score

print("Accuracy score predicting vax pct")
print(accuracy_score(y_vax_test, y_vax_pred))

Accuracy score predicting vax pct
0.6469833119383825


In [83]:
# Get confusion matrix

vax_matrix = confusion_matrix(y_vax_test, y_vax_pred)

# Create a DataFrame from the confusion matrix.
matrix_vax_df = pd.DataFrame(vax_matrix, 
                         index=["Actual 0-low_vax", "Actual 1-high_vax"], 
                         columns=["Predicted 0-low_vax", "Predicted 1-high_vax"])

matrix_vax_df

Predicted 0-low_vax  Predicted 1-high_vax
Actual 0-low_vax                   271                   117
Actual 1-high_vax                  158                   233

In [84]:
# Classification report 
vax_report = classification_report(y_vax_test, y_vax_pred)
print(vax_report)

              precision    recall  f1-score   support

           0       0.63      0.70      0.66       388
           1       0.67      0.60      0.63       391

    accuracy                           0.65       779
   macro avg       0.65      0.65      0.65       779
weighted avg       0.65      0.65      0.65       779



In [97]:
X_vax = X_econ_test_scaled[:, 0]
X_vax

array([ 2.25012101, -1.02162759, -0.78368223, -0.7241959 , -1.02162759,
        0.58450354, -1.25957294,  0.76296256, -0.90265491, -1.61649097,
       -0.36727787,  2.78549806,  0.0491265 ,  0.10861284,  0.10861284,
       -0.12933251,  0.70347622,  0.28707185,  0.22758552, -1.43803195,
       -0.48625054, -1.25957294, -0.78368223,  0.8224489 , -0.06984618,
        2.19063468,  0.58450354,  0.28707185, -0.84316857, -0.12933251,
       -1.73546364, -0.60522322, -1.61649097, -0.12933251, -1.37854562,
        0.22758552,  1.00090791,  0.0491265 , -0.96214125,  0.22758552,
       -1.43803195,  0.40604453,  0.0491265 ,  0.52501721,  1.06039425,
       -0.18881885, -1.49751829, -0.96214125, -1.67597731, -0.7241959 ,
        1.00090791, -0.12933251,  0.46553087, -1.31905928, -1.2000866 ,
        0.16809918,  1.35782594, -1.37854562, -1.08111392,  0.16809918,
       -0.36727787, -1.14060026, -0.78368223,  0.28707185,  0.0491265 ,
       -1.08111392,  0.22758552,  0.16809918, -0.7241959 ,  0.16

In [98]:
y_vax = X_econ_test_scaled[:, 1]
y_vax

array([-1.61720536e-01,  3.12298936e+00,  4.11423772e-02,  2.90194092e-01,
       -6.31035540e-01, -8.62333213e-01,  3.54773534e-01,  1.17740104e+00,
       -8.73799079e-02, -4.91266671e-01, -1.50013478e+00, -1.02933438e+00,
        8.29959396e-01, -1.59810031e+00, -6.57065370e-01,  9.45820432e-01,
       -1.28128615e+00, -1.12786577e+00,  1.65067002e-01,  9.51118342e-02,
        1.43493366e-01, -3.52275867e-01, -6.64428708e-02,  6.69890089e-01,
        2.46460442e+00,  2.31535730e+00, -6.33157537e-01, -1.00819222e-01,
        1.45460458e+00, -1.44326526e+00,  3.84835158e-01, -3.12665256e-01,
        7.90914651e-01, -2.46741883e-01,  4.52526863e-01,  2.21151374e-02,
       -1.33992400e+00, -1.31318684e+00,  3.65029853e-01, -2.74893710e-01,
       -2.69800917e-01,  2.49077572e+00,  1.60569077e+00, -8.46630435e-01,
       -1.29338154e+00, -7.00566308e-01,  2.47882180e+00, -6.61309364e-01,
       -3.83822889e-01,  1.33244829e+00, -4.64812441e-01, -8.40052245e-01,
       -5.18640432e-01,  

In [99]:
Z = y_vax_test.values.reshape(-1,1)
Z

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
    

In [100]:
df_x_vax = pd.DataFrame(X_vax)
df_y_vax = pd.DataFrame(y_vax)
df_z_vax = pd.DataFrame(Z)

In [101]:
df_x_vax.rename(columns = {0:'X_vax'}, inplace = True)
df_x_vax

X_vax
0    2.250121
1   -1.021628
2   -0.783682
3   -0.724196
4   -1.021628
..        ...
774 -0.486251
775 -1.200087
776 -0.248305
777 -1.140600
778  1.357826

[779 rows x 1 columns]

In [102]:
df_y_vax.rename(columns = {0:'y_vax'}, inplace = True)
df_y_vax

y_vax
0   -0.161721
1    3.122989
2    0.041142
3    0.290194
4   -0.631036
..        ...
774 -0.676163
775  0.816874
776 -0.722069
777 -0.498269
778  2.529255

[779 rows x 1 columns]

In [103]:
df_z_vax.rename(columns = {0:'z_vax'}, inplace = True)
df_z_vax

z_vax
0        1
1        1
2        1
3        1
4        0
..     ...
774      0
775      0
776      1
777      1
778      1

[779 rows x 1 columns]

In [104]:
df_xy_vax = pd.concat([df_x_vax, df_y_vax], axis=1,
)
df_xy_vax

X_vax     y_vax
0    2.250121 -0.161721
1   -1.021628  3.122989
2   -0.783682  0.041142
3   -0.724196  0.290194
4   -1.021628 -0.631036
..        ...       ...
774 -0.486251 -0.676163
775 -1.200087  0.816874
776 -0.248305 -0.722069
777 -1.140600 -0.498269
778  1.357826  2.529255

[779 rows x 2 columns]

In [105]:
df_xyz_vax = pd.concat([df_xy_vax, df_z_vax], axis=1
)
df_xyz_vax

X_vax     y_vax  z_vax
0    2.250121 -0.161721      1
1   -1.021628  3.122989      1
2   -0.783682  0.041142      1
3   -0.724196  0.290194      1
4   -1.021628 -0.631036      0
..        ...       ...    ...
774 -0.486251 -0.676163      0
775 -1.200087  0.816874      0
776 -0.248305 -0.722069      1
777 -1.140600 -0.498269      1
778  1.357826  2.529255      1

[779 rows x 3 columns]

In [107]:
# Creating 3D scatterplot of predicting case rate
# Create a 3D scatter plot with predictions


fig_vax = px.scatter_3d(df_xyz_vax, x="X_vax", y="y_vax", z="z_vax", 
                 opacity=0.8,
                 labels=dict(X_vax="Unemployment Rate", 
                             y_vax="Median Income",
                             z_vax="Median Split for Vax Rate",))
fig_vax.show()

In [93]:
df.to_csv("all_data_merged_med_split.csv", index=False)